# Creating a tensor

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [5]:
if torch.cuda.is_available():
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available")

Using GPU: NVIDIA GeForce MX250


In [6]:
import torch
print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected by PyTorch.")


Torch version: 2.5.1+cu121
CUDA available: True
GPU name: NVIDIA GeForce MX250


In [7]:
a = torch.empty(2, 5)
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [8]:
a = torch.zeros(2, 3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [9]:
a = torch.ones(2, 3)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [10]:
a = torch.rand(2, 3)
print(a)

tensor([[0.2829, 0.9603, 0.1209],
        [0.2987, 0.7570, 0.7276]])


In [11]:
a = torch.rand(2, 3)
print(a)

tensor([[0.2808, 0.9354, 0.3420],
        [0.8374, 0.1491, 0.3747]])


In [12]:
torch.manual_seed(234)
a = torch.rand(2, 3)
print(a)

tensor([[0.9276, 0.5817, 0.0962],
        [0.0014, 0.5745, 0.7127]])


In [13]:
torch.manual_seed(234)
a = torch.rand(2, 3)
print(a)

tensor([[0.9276, 0.5817, 0.0962],
        [0.0014, 0.5745, 0.7127]])


In [14]:
torch.tensor([[1, 24, 4], [23, 2, 132], [13, 13, 21]])

tensor([[  1,  24,   4],
        [ 23,   2, 132],
        [ 13,  13,  21]])

In [15]:
a = torch.arange(2, 12, 4) # Print an arithmetic progression
print(a)

b = torch.linspace(2, 12, 4) # Print evenly spaced values
print(b)

c = torch.eye(4)
print(c)

d = torch.full((3, 7), 4)
print(d)

tensor([ 2,  6, 10])
tensor([ 2.0000,  5.3333,  8.6667, 12.0000])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4]])


In [21]:
d.shape
d.dtype

torch.int64

In [17]:
e = torch.empty_like(d)
print(e)

tensor([[4669258990080,             0,             0,             0,
                     0,             0,             0],
        [            0,             0,             0,             0,
                     0,             0,             0],
        [            0,             0,             0,             0,
                     0,             0,             0]])


In [18]:
f = torch.zeros_like(d)
print(f)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])


In [ ]:
f = torch.rand_like(d, dtype=torch.float32)  # Breaks because of datatype issue
print(f)

# rand function generates floating point numbers between 0 and 1, so if your original tensor was of int datatype, it wouldn't work

tensor([[0.3646, 0.0531, 0.1347, 0.9168, 0.8947, 0.1901, 0.8059],
        [0.9505, 0.7176, 0.3519, 0.9520, 0.5670, 0.6915, 0.0761],
        [0.4416, 0.8761, 0.4408, 0.1783, 0.9585, 0.0374, 0.3687]])


# Tensor datatypes

In [ ]:
f.dtype

torch.int64

In [ ]:
# assigning while creating
torch.tensor([[2, 3, 4], [3, 4, 5], [3, 5, 2]], dtype = float)

tensor([[2., 3., 4.],
        [3., 4., 5.],
        [3., 5., 2.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [ ]:
# Change the datatype
f.to(torch.float32)

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

# Mathematical operations

In [4]:
x = torch.tensor([[1, 4, 2], [2, 43, 2]])
y = torch.rand_like(x, dtype=float)
print(x, y)

tensor([[ 1,  4,  2],
        [ 2, 43,  2]]) tensor([[0.4565, 0.7646, 0.8988],
        [0.3029, 0.7319, 0.2282]], dtype=torch.float64)


### Scalar operations

In [19]:
x+2
x*2
x-3
x/2
x//3
x**4
x%7

tensor([[1, 4, 2],
        [2, 1, 2]])

## Element-wise operations

In [21]:
x+y
x*y
x**y
x/y
x//y
x-y
x%y

tensor([[0.0869, 0.1770, 0.2024],
        [0.1828, 0.5504, 0.1744]], dtype=torch.float64)

In [ ]:
torch.abs(x)
torch.neg(x)
torch.round(y)
torch.floor(y)
torch.ceil(x)
torch.clamp(y, min=0.7, max=0.8) # Lesser than 0.7 will become 0.7, more than 0.8 will become 0.8, the ones in between will remain the same


tensor([[0.7000, 0.7646, 0.8000],
        [0.7000, 0.7319, 0.7000]], dtype=torch.float64)

## Reduction operations

In [41]:
z = torch.randint(size=(2,3), low=2, high=5)
z

tensor([[3, 2, 4],
        [2, 4, 4]])

In [ ]:
torch.sum(z)
torch.sum(z, dim=0) # sum accross columns
torch.sum(z, dim=1) # sum accross rows
torch.mean(z, dtype=torch.float32)
torch.mean(z, dim=0, dtype=torch.float32) # mean accross columns
torch.mean(z, dim=1, dtype=torch.float32) # mean accross rows
torch.argmax(z) # compresses into a 1-d array and shows the 0-based index of the maximum element
torch.argmin(z) # # compresses into a 1-d array and shows the 0-based index of the minimum element

tensor(2)

## Matrix operations

In [78]:
m = torch.randint(size=(2,3), low=21, high=28)
n = torch.randint(size=(3,2), low=0, high=5)

In [79]:
o = torch.matmul(m, n)
o

tensor([[ 85, 188],
        [ 98, 192]])

In [58]:
sqmat = torch.rand(size=(3, 3))
torch.det(sqmat)
torch.inverse(sqmat)

tensor([[ 0.9920, -0.5856,  0.2893],
        [ 1.0987,  0.8093, -1.1590],
        [-1.3702,  0.4587,  1.3768]])

## Comparison

In [67]:
nT =  n.T
m > nT
m < nT
m == nT


tensor([[False, False, False],
        [False, False, False]])

## Special functions

In [68]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[6., 8., 1.],
        [9., 1., 0.]])

In [69]:
# log
torch.log(k)

tensor([[1.7918, 2.0794, 0.0000],
        [2.1972, 0.0000,   -inf]])

In [70]:
# exp
torch.exp(k)

tensor([[4.0343e+02, 2.9810e+03, 2.7183e+00],
        [8.1031e+03, 2.7183e+00, 1.0000e+00]])

In [71]:
# sqrt
torch.sqrt(k)

tensor([[2.4495, 2.8284, 1.0000],
        [3.0000, 1.0000, 0.0000]])

In [72]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.9997, 0.7311],
        [0.9999, 0.7311, 0.5000]])

In [ ]:
# softmax
torch.softmax(k, dim=0) # In this one you have to specify the dimension accross which the exponents must be added

tensor([[4.7426e-02, 9.9909e-01, 7.3106e-01],
        [9.5257e-01, 9.1105e-04, 2.6894e-01]])

In [74]:
# relu
torch.relu(k)

tensor([[6., 8., 1.],
        [9., 1., 0.]])

## In-place operations

In [76]:
p = torch.rand(2,3)
q = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0664, 0.3628, 0.3452],
        [0.7661, 0.6234, 0.0223]])
tensor([[0.0667, 0.9495, 0.2550],
        [0.6844, 0.4463, 0.5226]])


In [82]:
p.add_(q) # Operations followed by an '_' are in-place operations, they overwrite the argument tensor
p

tensor([[0.7454, 0.6800, 1.1053],
        [0.4644, 0.9387, 0.9924]])

In [83]:
q

tensor([[0.7111, 0.0646, 0.2110],
        [0.3760, 0.3561, 0.9439]])

In [84]:
torch.relu(p)  # This operation created a completely new tensor in memory, but we don't want that

tensor([[0.7454, 0.6800, 1.1053],
        [0.4644, 0.9387, 0.9924]])

In [86]:
p.relu_()
p

tensor([[0.7454, 0.6800, 1.1053],
        [0.4644, 0.9387, 0.9924]])

# Copying a tensor

In [87]:
a = torch.rand(2,3)
a

tensor([[0.5409, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]])

In [88]:
b = a

In [89]:
b

tensor([[0.5409, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]])

In [90]:
a

tensor([[0.5409, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]])

In [91]:
a[0][0] = 0

In [92]:
a

tensor([[0.0000, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]])

In [93]:
b

tensor([[0.0000, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]])

In [94]:
id(a)

3039997623376

In [95]:
id(b)

3039997623376

In [96]:
b = a.clone()

In [97]:
a

tensor([[0.0000, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]])

In [98]:
b

tensor([[0.0000, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]])

In [99]:
b[0][0] = 32

In [100]:
a

tensor([[0.0000, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]])

In [101]:
b

tensor([[32.0000,  0.7595,  0.8189],
        [ 0.6067,  0.2484,  0.1703]])

In [102]:
id(a)

3039997623376

In [103]:
id(b)

3040003747872

## Tensor operations on GPU

In [105]:
torch.cuda.is_available()

True

In [4]:
device = torch.device('cuda')

In [108]:
a1 = torch.rand((2, 3), device=device)
a1

tensor([[0.6140, 0.9653, 0.4703],
        [0.1506, 0.3169, 0.1083]], device='cuda:0')

In [109]:
a.to(device)

tensor([[0.0000, 0.7595, 0.8189],
        [0.6067, 0.2484, 0.1703]], device='cuda:0')

In [6]:
# Comparing CPU time and GPU time

# CPU performance
import time as ti
cpu_mat1 = torch.rand(size=(10000, 10000))
cpu_mat2 = torch.rand(size=(10000, 10000))

cpu_start_time = ti.time()
cpu_result = torch.matmul(cpu_mat1, cpu_mat2)
cpu_time_taken = ti.time()-cpu_start_time


gpu_mat1 = torch.rand(size=(10000, 10000), device=device)
gpu_mat2 = torch.rand(size=(10000, 10000), device=device)

torch.cuda.synchronize()   # make sure GPU is idle before timing
gpu_start_time = ti.time()
gpu_result = torch.matmul(gpu_mat1, gpu_mat2)
torch.cuda.synchronize()   # wait until GPU finishes before stopping timer
gpu_time_taken = ti.time()-gpu_start_time



print(f"CPU performance: {cpu_time_taken}\n")
print(f"GPU performance: {gpu_time_taken}\n")
print(f"Gain = {cpu_time_taken/gpu_time_taken}")



CPU performance: 12.417127847671509

GPU performance: 1.9641263484954834

Gain = 6.321959815458411


## Reshaping tensors

In [7]:
g = torch.rand(4, 4)
g

tensor([[0.5319, 0.0379, 0.8996, 0.9044],
        [0.6507, 0.4527, 0.7818, 0.2040],
        [0.7000, 0.6334, 0.5927, 0.7164],
        [0.8657, 0.7853, 0.1421, 0.5865]])

In [8]:
g.T

tensor([[0.5319, 0.6507, 0.7000, 0.8657],
        [0.0379, 0.4527, 0.6334, 0.7853],
        [0.8996, 0.7818, 0.5927, 0.1421],
        [0.9044, 0.2040, 0.7164, 0.5865]])

In [ ]:
g.reshape(2, 2, 2, 2) # Product of the re-shaped tensor should be the same as before

tensor([[[[0.5319, 0.0379],
          [0.8996, 0.9044]],

         [[0.6507, 0.4527],
          [0.7818, 0.2040]]],


        [[[0.7000, 0.6334],
          [0.5927, 0.7164]],

         [[0.8657, 0.7853],
          [0.1421, 0.5865]]]])

In [11]:
g.flatten()

tensor([0.5319, 0.0379, 0.8996, 0.9044, 0.6507, 0.4527, 0.7818, 0.2040, 0.7000,
        0.6334, 0.5927, 0.7164, 0.8657, 0.7853, 0.1421, 0.5865])

In [12]:
h = torch.rand(4, 3, 5)
h

tensor([[[0.6225, 0.8567, 0.8652, 0.1885, 0.5776],
         [0.7748, 0.2137, 0.3635, 0.9749, 0.9561],
         [0.8204, 0.6781, 0.2814, 0.0554, 0.2398]],

        [[0.1135, 0.1337, 0.1441, 0.5368, 0.6197],
         [0.9490, 0.7929, 0.2257, 0.3062, 0.9445],
         [0.7350, 0.1768, 0.8332, 0.9095, 0.6016]],

        [[0.7707, 0.0609, 0.6515, 0.0235, 0.1351],
         [0.5042, 0.5480, 0.9149, 0.9155, 0.4896],
         [0.8584, 0.2766, 0.0659, 0.8435, 0.5903]],

        [[0.9156, 0.3819, 0.4303, 0.4667, 0.2764],
         [0.8185, 0.8247, 0.8883, 0.4027, 0.7200],
         [0.1472, 0.6346, 0.0031, 0.1355, 0.2882]]])

In [ ]:
h.permute(2, 1, 0).shape # Changing the shape by making a new permutation of the previous dimensions

torch.Size([5, 3, 4])

In [ ]:
i = torch.rand(3, 226, 226)
i.unsqueeze(0).shape # Adding a unit dimension on an index of your choice

torch.Size([1, 3, 226, 226])

## Transitioning between Numpy and Pytorch

In [17]:
import numpy as np

In [ ]:
# Pytorch to numpy
j = torch.tensor([1, 2, 3])
k = j.numpy()
print(k)
print(j)

[1 2 3]
tensor([1, 2, 3])


In [20]:
# Numpy to pytorch
l = np.array([1, 2, 3])
r = torch.from_numpy(l)
print(l)
print(r)

[1 2 3]
tensor([1, 2, 3])
