# Creating a tensor

In [1]:
import torch
print(torch.__version__)

2.5.1+cu121


In [2]:
if torch.cuda.is_available():
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available")

Using GPU: NVIDIA GeForce MX250


In [3]:
import torch
print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU name:", torch.cuda.get_device_name(0))
else:
    print("No GPU detected by PyTorch.")


Torch version: 2.5.1+cu121
CUDA available: True
GPU name: NVIDIA GeForce MX250


In [6]:
a = torch.empty(2, 5)
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [9]:
a = torch.zeros(2, 3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
a = torch.ones(2, 3)
print(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [12]:
a = torch.rand(2, 3)
print(a)

tensor([[0.3055, 0.0270, 0.0884],
        [0.8319, 0.1860, 0.4307]])


In [13]:
a = torch.rand(2, 3)
print(a)

tensor([[0.0903, 0.9583, 0.1554],
        [0.0384, 0.1026, 0.7071]])


In [15]:
torch.manual_seed(234)
a = torch.rand(2, 3)
print(a)

tensor([[0.9276, 0.5817, 0.0962],
        [0.0014, 0.5745, 0.7127]])


In [16]:
torch.manual_seed(234)
a = torch.rand(2, 3)
print(a)

tensor([[0.9276, 0.5817, 0.0962],
        [0.0014, 0.5745, 0.7127]])


In [20]:
torch.tensor([[1, 24, 4], [23, 2, 132], [13, 13, 21]])

tensor([[  1,  24,   4],
        [ 23,   2, 132],
        [ 13,  13,  21]])

In [26]:
a = torch.arange(2, 12, 4) # Print an arithmetic progression
print(a)

b = torch.linspace(2, 12, 4) # Print evenly spaced values
print(b)

c = torch.eye(4)
print(c)

d = torch.full((3, 7), 4)
print(d)

tensor([ 2,  6, 10])
tensor([ 2.0000,  5.3333,  8.6667, 12.0000])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4]])


In [27]:
d.shape

torch.Size([3, 7])

In [32]:
e = torch.empty_like(d)
print(e)

tensor([[6522642236672,             0,             0,             0,
                     0,             0,             0],
        [            0,             0,             0,             0,
                     0,             0,             0],
        [            0,             0,             0,             0,
                     0,             0,             0]])


In [33]:
f = torch.zeros_like(d)
print(f)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]])


In [ ]:
f = torch.rand_like(d)  # Breaks because of datatype issue
print(f)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

# Tensor datatypes

In [35]:
f.dtype

torch.int64

In [37]:
# assigning while creating
torch.tensor([[2, 3, 4], [3, 4, 5], [3, 5, 2]], dtype = float)

tensor([[2., 3., 4.],
        [3., 4., 5.],
        [3., 5., 2.]], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [ ]:
# Change the datatype
f.to(torch.float32)

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])